export const paths = {
  home: '/',
  welcome: '/welcome',
  login: '/login',
  community: '/community',
  projects: '/projects',
  project: (projectId: string) => `/projects/${encodeURIComponent(projectId)}`,
  projectSubProjects: (projectId: string) => `/projects/${encodeURIComponent(projectId)}/sub-projects`,
  projectEvents: (projectId: string) => `/projects/${encodeURIComponent(projectId)}/events`,
  projectClubs: (projectId: string) => `/projects/${encodeURIComponent(projectId)}/clubs`,
  projectPositions: (projectId: string) => `/projects/${encodeURIComponent(projectId)}/positions`,
  projectNotes: (projectId: string) => `/projects/${encodeURIComponent(projectId)}/notes`,
  volunteering: '/volunteering',
  events: '/events',
  event: (eventId: string) => `/event/${encodeURIComponent(eventId)}`,
  eventEdit: (eventId: string) => `/event/${encodeURIComponent(eventId)}/edit`,
  eventAdmin: (eventId: string) => `/event/${encodeURIComponent(eventId)}/admin`,
  clubs: '/clubs',
  club: (clubId: string) => `/clubs/${encodeURIComponent(clubId)}`,
  clubEdit: (clubId: string) => `/clubs/${encodeURIComponent(clubId)}/edit`,
  positionEdit: (positionId: string) => `/positions/${encodeURIComponent(positionId)}/edit`,
  profile: '/profile',
  settings: '/settings',
} as const
