name: (dev) [database-migrations] Migrate D1 Databases

on:
  push:
    branches:
      - dev
    paths:
      - '.github/workflows/db-dev.yml'
  workflow_dispatch:

jobs:
  backend-migrations:
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install project dependencies
        run: npm install

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Update wrangler config with environment variables
        run: |
          jq_filter='.d1_databases[0].database_id = $dbid0
          | .d1_databases[0].database_name = $dbname0
          | .d1_databases[1].database_id = $dbid1
          | .d1_databases[1].database_name = $dbname1
          | .r2_buckets[0].bucket_name = $bucketname
          | .vars.MEMBERSHIP_NUMBER_PREFIX = $mprefix
          | .vars.SMTP_HOST = $smtpHost
          | .vars.SMTP_PORT = $smtpPort
          | .vars.SMTP_USER = $smtpUser
          | .account_id = $accountId'

          jq \
            --arg dbid0 "${{ vars.MEMBERS_DB_ID }}" \
            --arg dbname0 "${{ vars.MEMBERS_DB_NAME }}" \
            --arg dbid1 "${{ vars.VMS_DB_ID }}" \
            --arg dbname1 "${{ vars.VMS_DB_NAME }}" \
            --arg bucketname "${{ vars.BUCKET_NAME }}" \
            --arg mprefix "${{ vars.MEMBERSHIP_NUMBER_PREFIX }}" \
            --arg smtpHost "${{ vars.SMTP_HOST }}" \
            --arg smtpPort "${{ vars.SMTP_PORT }}" \
            --arg smtpUser "${{ vars.SMTP_USER }}" \
            --arg accountId "${{ vars.CLOUDFLARE_ACCOUNT_ID }}" \
            "$jq_filter" \
            wrangler.jsonc > wrangler.local.jsonc

      - name: Migrate D1 Databases
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: wrangler d1 migrations apply ${{ vars.MEMBERS_DB_NAME }} --remote --config wrangler.local.jsonc && wrangler d1 migrations apply ${{ vars.VMS_DB_NAME }} --remote --config wrangler.local.jsonc
  
  telegram-ms-migrations:
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: ./telegram-ms
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install project dependencies
        run: npm install

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Update wrangler config with environment variables
        run: |
          jq_filter='.d1_databases[0].database_id = $dbid0
          | .d1_databases[0].database_name = $dbname0
          | .vars.MAIN_CHANNEL = $mainChannel
          | .vars.SMTP_HOST = $smtpHost
          | .vars.SMTP_PORT = $smtpPort
          | .vars.SMTP_USER = $smtpUser
          | .vars.TELEGRAM_MS = $telegramMs
          | .account_id = $accountId'

          jq \
            --arg dbid0 "${{ vars.TELEGRAM_DB_ID }}" \
            --arg dbname0 "${{ vars.TELEGRAM_DB_NAME }}" \
            --arg mainChannel "${{ vars.MAIN_CHANNEL }}" \
            --arg smtpHost "${{ vars.SMTP_HOST }}" \
            --arg smtpPort "${{ vars.SMTP_PORT }}" \
            --arg smtpUser "${{ vars.SMTP_USER }}" \
            --arg telegramMs "${{ vars.TELEGRAM_MS }}" \
            --arg accountId "${{ vars.CLOUDFLARE_ACCOUNT_ID }}" \
            "$jq_filter" \
            wrangler.jsonc > wrangler.local.jsonc

      - name: Migrate D1 Database
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: wrangler d1 migrations apply ${{ vars.TELEGRAM_DB_NAME }} --remote --config wrangler.local.jsonc