name: Deploy to Cloudflare Worker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install project dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Set secrets in Worker
        run: |
          echo "${{ secrets.ADMIN_PASSWORD }}" | wrangler secret put ADMIN_PASSWORD --env production
          echo "${{ env.MOODLE_API_URL }}" | wrangler secret put MOODLE_API_URL --env production
          echo "${{ secrets.MOODLE_API_TOKEN }}" | wrangler secret put MOODLE_API_TOKEN --env production
          echo "${{ env.SMTP_HOST }}" | wrangler secret put SMTP_HOST --env production
          echo "${{ env.SMTP_PORT }}" | wrangler secret put SMTP_PORT --env production
          echo "${{ env.SMTP_USER }}" | wrangler secret put SMTP_USER --env production
          echo "${{ secrets.SMTP_PASS }}" | wrangler secret put SMTP_PASS --env production
          echo "${{ secrets.JWT_SECRET }}" | wrangler secret put JWT_SECRET --env production
          echo "${{ env.MEMBERSHIP_NUMBER_PREFIX }}" | wrangler secret put MEMBERSHIP_NUMBER_PREFIX --env production
          echo "${{ secrets.GOOGLE_API_KEY }}" | wrangler secret put GOOGLE_API_KEY --env production

      - name: Publish Worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: wrangler deploy
