name: Deploy to Cloudflare Worker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install project dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Install Wrangler
        run: npm install -g wrangler


      - name: Publish Worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: wrangler deploy

      - name: Set secrets in Worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          echo "${{ secrets.ADMIN_PASSWORD }}" | wrangler secret put ADMIN_PASSWORD
          echo "${{ secrets.MOODLE_API_TOKEN }}" | wrangler secret put MOODLE_API_TOKEN
          echo "${{ secrets.SMTP_PASS }}" | wrangler secret put SMTP_PASS
          echo "${{ secrets.JWT_SECRET }}" | wrangler secret put JWT_SECRET
          echo "${{ secrets.GOOGLE_API_KEY }}" | wrangler secret put GOOGLE_API_KEY

      - name: Set env vars in Worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          wrangler vars put MOODLE_API_URL="${{ env.MOODLE_API_URL }}"
          wrangler vars put SMTP_HOST="${{ env.SMTP_HOST }}"
          wrangler vars put SMTP_PORT="${{ env.SMTP_PORT }}"
          wrangler vars put SMTP_USER="${{ env.SMTP_USER }}"
          wrangler vars put MEMBERSHIP_NUMBER_PREFIX="${{ env.MEMBERSHIP_NUMBER_PREFIX }}"
